//! 模組整合包常見術語。
//!
//! 香草 Minecraft 大表只涵蓋遊戲原生內容；這份清單補上整合包最常見的
//! 載入器、任務、配方檢視器、能源／流體與大型模組術語。只放有明確
//! 台灣繁中用法的詞，模組專有名詞保留原名或以括號補充，避免過度翻譯。

pub(super) const TERMS: &[(&str, &str)] = &[
    // ── 整合包與模組基礎 ─────────────────────────────────────
    ("Mod", "模組"),
    ("Modpack", "模組包"),
    ("Resource Pack", "資源包"),
    ("Data Pack", "資料包"),
    ("Shader Pack", "光影包"),
    ("Texture Pack", "材質包"),
    ("Language File", "語言檔"),
    ("Translation", "翻譯"),
    ("Traditional Chinese", "繁體中文"),
    ("Simplified Chinese", "簡體中文"),
    ("Configuration File", "設定檔"),
    ("Config Screen", "設定畫面"),
    ("Mod Loader", "模組載入器"),
    ("Dependency", "相依模組"),
    ("Required Dependency", "必要相依模組"),
    ("Optional Dependency", "選用相依模組"),
    ("Compatible Version", "相容版本"),
    ("Game Instance", "遊戲實例"),
    ("Launcher Profile", "啟動器設定檔"),
    ("Client Side", "用戶端"),
    ("Server Side", "伺服器端"),
    ("Dedicated Server", "專用伺服器"),
    ("Singleplayer", "單人遊戲"),
    ("Multiplayer", "多人遊戲"),
    ("World Generation", "世界生成"),
    ("World Seed", "世界種子"),
    ("Chunk Loading", "區塊載入"),
    ("Chunk Loader", "區塊載入器"),
    ("Block Entity", "方塊實體"),
    ("Loot Table", "戰利品表"),
    ("Registry", "註冊表"),
    ("Namespace", "命名空間"),
    ("Identifier", "識別碼"),
    ("Key Binding", "按鍵綁定"),
    ("Search Bar", "搜尋列"),
    ("Recipe Viewer", "配方檢視器"),
    ("Confirm", "確認"),
    ("Cancel", "取消"),
    ("Apply", "套用"),
    ("Reset", "重設"),
    ("Save", "儲存"),
    ("Enabled", "已啟用"),
    ("Disabled", "已停用"),
    ("Required", "必要"),
    ("Optional", "選用"),
    ("Default", "預設"),
    ("Input", "輸入"),
    ("Output", "輸出"),
    ("Capacity", "容量"),
    ("Transfer Rate", "傳輸速率"),
    ("Fluid Tank", "流體儲罐"),
    ("Energy Storage", "能量儲存"),
    ("Machine Frame", "機器框架"),
    ("Upgrade", "升級"),
    ("Filter", "篩選器"),
    ("Whitelist", "允許清單"),
    ("Blacklist", "封鎖清單"),

    // ── 任務、指南書與配方檢視器 ─────────────────────────────
    ("FTB Quests", "FTB 任務"),
    ("Quest Book", "任務書"),
    ("Quest Chapter", "任務章節"),
    ("Quest Reward", "任務獎勵"),
    ("Task Objective", "任務目標"),
    ("Optional Task", "選用任務"),
    ("Team Quest", "團隊任務"),
    ("Party Quest", "小隊任務"),
    ("Claim Reward", "領取獎勵"),
    ("Reward Table", "獎勵表"),
    ("Reputation", "聲望"),
    ("Progression", "進度"),
    ("Milestone", "里程碑"),
    ("Guide Book", "指南書"),
    ("Book Entry", "書籍條目"),
    ("Book Category", "書籍分類"),
    ("Multiblock Structure", "多方塊結構"),
    ("Recipe Page", "配方頁面"),
    ("Image Page", "圖片頁面"),
    ("Entity Page", "實體頁面"),
    ("Advancement Page", "進度頁面"),
    ("Link Page", "連結頁面"),
    ("Just Enough Items", "JEI（物品與配方）"),
    ("Roughly Enough Items", "REI（物品與配方）"),
    ("EMI", "EMI（物品與配方）"),
    ("Recipe Category", "配方分類"),
    ("Recipe Type", "配方類型"),
    ("Item List", "物品清單"),
    ("Bookmark", "書籤"),
    ("Ingredient", "材料"),
    ("Ingredient List", "材料清單"),
    ("Transfer Recipe", "轉移配方"),
    ("Show Uses", "查看用途"),
    ("Show Recipes", "查看配方"),
    ("Crafting Recipe", "合成配方"),
    ("Smelting Recipe", "熔煉配方"),

    // ── Create ───────────────────────────────────────────────
    ("Andesite Alloy", "安山岩合金"),
    ("Brass Ingot", "黃銅錠"),
    ("Zinc Ingot", "鋅錠"),
    ("Electron Tube", "電子管"),
    ("Precision Mechanism", "精密機構"),
    ("Mechanical Press", "機械壓床"),
    ("Mechanical Mixer", "機械攪拌器"),
    ("Mechanical Crafter", "機械合成器"),
    ("Encased Fan", "封裝風扇"),
    ("Crushing Wheel", "粉碎輪"),
    ("Portable Storage Interface", "可攜式儲存介面"),
    ("Stress Unit", "應力單位"),
    ("Kinetic Stress", "動力應力"),
    ("Schematicannon", "藍圖砲"),
    ("Engineer's Goggles", "工程師護目鏡"),
    ("Super Glue", "超級膠"),
    ("Large Cogwheel", "大型齒輪"),
    ("Steam Engine", "蒸汽引擎"),
    ("Train Station", "火車站"),
    ("Train Schedule", "火車時刻表"),
    ("Train Track", "火車軌道"),
    ("Bogey", "轉向架"),
    ("Create Contraption", "Create 機械結構"),

    // ── Mekanism ─────────────────────────────────────────────
    ("Enrichment Chamber", "富集室"),
    ("Metallurgic Infuser", "冶金浸滲器"),
    ("Purification Chamber", "純化室"),
    ("Chemical Injection Chamber", "化學注入室"),
    ("Digital Miner", "數位採礦機"),
    ("Atomic Disassembler", "原子分解器"),
    ("Energy Cube", "能量立方"),
    ("Refined Obsidian", "精製黑曜石"),
    ("Atomic Alloy", "原子合金"),
    ("Radiation Protection", "輻射防護"),
    ("Chemical Tank", "化學品儲罐"),
    ("Pressurized Tube", "加壓管"),
    ("Basic Tier", "基礎階級"),
    ("Advanced Tier", "進階階級"),
    ("Elite Tier", "精英階級"),
    ("Ultimate Tier", "終極階級"),

    // ── Applied Energistics 2／Refined Storage ───────────────
    ("Certus Quartz", "賽特斯石英"),
    ("Charged Certus Quartz", "充能賽特斯石英"),
    ("Fluix Crystal", "福斯水晶"),
    ("Applied Energistics 2", "應用能源 2"),
    ("ME System", "ME 系統"),
    ("ME Drive", "ME 驅動器"),
    ("ME Controller", "ME 控制器"),
    ("Storage Cell", "儲存元件"),
    ("Storage Bus", "儲存匯流排"),
    ("Import Bus", "輸入匯流排"),
    ("Export Bus", "輸出匯流排"),
    ("Pattern Provider", "樣板供應器"),
    ("Pattern Terminal", "樣板終端"),
    ("Molecular Assembler", "分子組裝器"),
    ("Inscriber", "壓印器"),
    ("Crafting CPU", "合成處理器"),
    ("Crafting Grid", "合成網格"),
    ("Auto Crafting", "自動合成"),
    ("Channels", "通道"),
    ("P2P Tunnel", "P2P 通道"),
    ("Quantum Network Bridge", "量子網路橋接器"),
    ("Quartz Enriched Iron", "富集石英鐵"),
    ("Storage Disk", "儲存磁碟"),
    ("Storage Grid", "儲存網格"),
    ("Wireless Grid", "無線網格"),
    ("External Storage", "外部儲存"),
    ("Importer", "匯入器"),
    ("Exporter", "匯出器"),
    ("Constructor", "建構器"),
    ("Destructor", "解構器"),
    ("Autocrafting Pattern", "自動合成樣板"),

    // ── Thermal／能源與機器 ─────────────────────────────────
    ("Pulverizer", "粉碎機"),
    ("Redstone Furnace", "紅石熔爐"),
    ("Induction Smelter", "感應熔煉爐"),
    ("Phytogenic Insolator", "植物培養機"),
    ("Fluxbore", "磁通鑽"),
    ("Satchel", "挎包"),
    ("Mana Pool", "魔力池"),
    ("Mana Spreader", "魔力散播器"),
    ("Lexica Botania", "植物魔法辭典"),
    ("Pure Daisy", "純潔雛菊"),
    ("Livingwood", "活木"),
    ("Livingrock", "活石"),
    ("Floral Fertilizer", "花肥"),
    ("Terrestrial Agglomeration Plate", "陸生聚合板"),
    ("Gaia Guardian", "蓋亞守護者"),
    ("Source Jar", "源質罐"),
    ("Spellbook", "法術書"),
    ("Spell Power", "法術強度"),
    ("Imbuement Chamber", "灌注室"),
    ("Enchanting Apparatus", "附魔裝置"),
    ("Glyph Press", "雕文壓印器"),
    ("Source Relay", "源質中繼器"),

    // ── Immersive Engineering／農業與生產 ─────────────────────
    ("Engineer's Manual", "工程師手冊"),
    ("Coke Oven", "焦爐"),
    ("Diesel Generator", "柴油發電機"),
    ("Garden Cloche", "溫室鐘罩"),
    ("Arc Furnace", "電弧爐"),
    ("Crusher", "粉碎機"),
    ("Excavator", "挖掘機"),
    ("Conveyor Belt", "輸送帶"),
    ("LV Wire", "低壓電線"),
    ("MV Wire", "中壓電線"),
    ("HV Wire", "高壓電線"),
    ("Wire Connector", "電線連接器"),
    ("Treated Wood", "防腐木"),
    ("Cooking Pot", "烹飪鍋"),
    ("Cutting Board", "砧板"),
    ("Skillet", "平底鍋"),
    ("Rich Soil", "肥沃土壤"),

    // ── KubeJS／Origins／Apotheosis ──────────────────────────
    ("Startup Script", "啟動腳本"),
    ("Server Script", "伺服器腳本"),
    ("Client Script", "用戶端腳本"),
    ("Event Handler", "事件處理器"),
    ("Recipe Event", "配方事件"),
    ("Script Event", "腳本事件"),
    ("Data Generation", "資料生成"),
    ("Origin", "起源"),
    ("Power Type", "能力類型"),
    ("Attribute Modifier", "屬性修飾器"),
    ("Resource Bar", "資源條"),
    ("Affix", "詞綴"),
    ("Gem Socket", "寶石插槽"),
    ("Rarity", "稀有度"),
    ("Salvaging", "拆解"),
    ("Augment", "增幅"),

    // ── 常見探索、殖民地與自動化模組 ─────────────────────────
    ("Waystone", "傳送石"),
    ("Warp Stone", "傳送石"),
    ("Bound Scroll", "綁定卷軸"),
    ("Return Scroll", "回程卷軸"),
    ("Colony", "殖民地"),
    ("Citizen", "居民"),
    ("Town Hall", "城鎮大廳"),
    ("Supply Camp", "補給營地"),
    ("Warehouse", "倉庫"),
    ("Courier", "快遞員"),
    ("Builder's Hut", "建築工坊"),
    ("Mob Crusher", "生物粉碎機"),
    ("Mob Slaughter Factory", "生物屠宰工廠"),
    ("Latex Processing Unit", "乳膠處理機"),
    ("Dissolution Chamber", "溶解室"),
    ("Pressure Chamber", "壓力室"),
    ("Air Compressor", "空氣壓縮機"),
    ("Pressure Tube", "壓力管"),
    ("Pneumatic Helmet", "氣動頭盔"),
    ("EMC", "EMC"),
    ("Philosopher's Stone", "賢者之石"),
    ("Transmutation Table", "轉換桌"),
    ("Klein Star", "克萊因之星"),
    ("Pocket Computer", "攜帶式電腦"),
    ("Advanced Computer", "進階電腦"),
    ("Peripheral", "周邊設備"),
    ("Lua", "Lua"),
    ("Backpack", "背包"),
    ("Pickup Upgrade", "拾取升級"),
    ("Deposit Upgrade", "存入升級"),
    ("Stack Upgrade", "堆疊升級"),
    ("Filter Upgrade", "篩選升級"),
];
